# Generated by Django 5.0 on 2023-12-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='born_date',
            field=models.CharField(max_length=80),
        ),
    ]
